---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: soju-admin
  namespace: soju-prod
spec:
  encryptedData:
    admin-password: AgAXnhAXaYPU/pAdY9D1Ki34IZcjAy3Cn652ZeXOI3IH6koMU0KV+8jO1fGSDgXC8DDxM4I4kXYp7pmLQG1Fj/fAXD73y8FX+CF+eMo83FBnM4RZO6IGBsgKFYPDbqT7cGaX6+pCmh1SxLgio5OFjecWQ+oPIGZCm5Sc/NxMqDPM7xFdJseDxeIeSC2j0qty/14ChgeOtLF0MT1z3irSOxLG7r7LR5hikxV2kQOLWuYQKsqnkFPSnJA2TvoSK/ivSDWqce6TWvAbVuOvk7gBPZHXq/YEd455SCpU3yBJQ/q0n9YgtL+4mxhLifqf59LJy2IIdYrfcpholQJvfTLcBnub8xgJR7Hnt20qhp7E3VYSN4mk2KqzndlY0z0cDatEkU7tziyeDFn8J+xL1lf4oIAyIJo0TWED6k3+MePfqeXprJJjcexMLAvDCs1frlTNUkDlg6zTWY5C8eqt3w6sJU03YrM5TTUBTRZBtWu7cZtUpH5eCtmPEgtH1z5rao+2nIE7CC/M5OW+1KqNPyx+3nL3myinWjJzjF/WGbiCzHF3MynUAo2OJCDpiYZYPaxEpsCnNlWMIBmPDpJtQli376aa+SaiPUMlgMkxaB+c4FZr++H9OXhhwlcWH/fxK/rxHHLBLTfKBA4QNEagVMAEHytOHR9kmJZ2pUcbkjqGs3v/f/QkJQBX+lLgCw+ujl4YNYW7e7dgNIunEbnapJ20YsfYJFZ71UvOswU=
    admin-username: AgAMXbL7EgWf+jeU4qWOa/Adkgfb3m1uYUS/JjWSUdnu0Hrc1uQcfhPqc1czGVtjzHAur/HZrxWb15O3OQolYbJ8AtniYxx+XcMIJ9gIG8QlKGL/wcYlaHSQEM8w2ky4mS/MkoK2ri9Qq0OP7xIGzvf8q2LHR3tnhvDcw7tZIUcXiX/9h2Gc49Mwt7skbuo3fZ8T9AMpB/p0lkYRR5cKv3MExdsw4v46EhYoiMyJVhVMw+EjTCgrU2/7Zfh7hkNwj269dsc5Lp8hvInxe9MhI0/PhsUa+Qh9o/ZZxCblYES1Nb0afV87EskyzGVmjWzcpzdtpvswi/hGiwf/JAnxneBlTus4D759COPH520FCziySzVqJZfQ4g9BhIbp7bQ5HeiBFVhWQP8byZpZlJBO7ikrIJeVynnemXzBekYue4KyY7I5/xJx9+/LweWPSWbwHYRxL2lnHAt5mqPpf8EaXfDLpVHYpZtw5l66eGpGIxLjMdlXtIeDrm65WEK+lRqFwG14lwUPQrVvKs6ml8FgS4umVEPfgSImfun9516zn1AJydOBZ8DLgcp2k6TGxvjTOsaqV4dr9Fh7ehTxBX2QYX4O4raRM1n6NX2s67Bkro5BiUnv7WxWIH+qRitBAdqZTkF+sS7JAKA7yuc2m5hG95VzHlwYHcJNogV0PMdvoWepyqXfI6pwvRDCy/BAB923fmyhFptwgQ==
  template:
    metadata:
      name: soju-admin
      namespace: soju-prod
