---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: akkoma-postgresql
  namespace: akkoma-prod
spec:
  encryptedData:
    postgres-password: AgAes/n4K2WmndEEBtN6d9LBJMZFguZ7wfpq0LJ1LWQswFk6ZmbL1EOW+QQvypGmvisN3A4goSDEsokf3wP53GeXy6jcQS5ig+mBbE9dKEEjk2qZiB26aFBbV1CSPmRcglhjYdeVKmrmZaE2u9AwLhpqmMp5Wi+d2TBZosbhY4tN00joihjAYP1RCWP1JhPMZu2WX3TJ2bf5DJLIkm/bP5C6nJb+xaD/2H6sQkDVJevKA2uCwm6yMM14afCTPSXJzAKip5RwRYCRcN684WY529HDflITiL9q2E0ifopnN93556HpMIzFyPOAniBntHlG0saEjPTCgx5XkXRnlECK3r2Ug3R5tN78HYgIlg3ABoBdpsxJYIjBqsdAsDKDHclv0yo39aIPAePeYs4MvOB2987rBUSuKuzVI6pDmOuTrRm525ffrCX8dsxN9YqSN/mpUgPIXWs4OlEW75Hc6Aj8olBG5vxNarzQOt87+boPV5SrPUI38nIE7qz6KUMVwpcSow1+QJzC5dWTb0jAdbCfqUVfD8C1eAKahcIbrtchoIC+B4nVzNP+sfvQAjNBs7OvARrbZuQTQLdZTQI8YvuXXG6DTB8NlVFSNZDYJbIV4BBf//X7yXnlkheP7+bfzAVkvpPSCofzRqiGS8/sohs5ZHH2xSOaIE9zBV+HAc9jXOdXT/V4pNLh85gir9UTIjmsUUGMZUXRd0ynVT0Woe/F4XLAz6V6fziZXbZfY6xqmGlVGg==
  template:
    metadata:
      name: akkoma-postgresql
      namespace: akkoma-prod
