---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCi2xJSvnv5CCGo0DRZ7jzzAsSHWc6yVC6CgZdbjlKtx6bPNONA6SmEkxPaV0J6o5ziwesWaay1R/TzlW3cTixQbd+HK14fCTjvNAq8oqb+rCoAh2KRj3ff/vil1pe7pDeFL7X6FlBUGBbUQMdASnzMm0n2sXpBq1HVhCCC+tvMMKlemUe9zvRduWE75V5wDVHpLUE40zRmAPM7yAtbKfaQGtjEdz+UA0FOMpNnxqVB2DGE2xbtnVIQiwa67tV2GCm3GwuwAGFWKVocWDDGlzvqGoBlMNQQLgifSoC8sccCW9hEiQS9ZMvhhL8qy+yiWx8xIuMNO1Kcu7ELSwMBeTe2xOK9OzD8t2ktSqqaurYCW7jFRycObjWBcYilz0ly3rDUfHZ4SvyToQTG6ozPOW4as1QBLtV33E2l1B5I3uaRop138a1viF+Sv952jwk4MKxx2gwRCJ96IcbZ4H/vn5t8kQd6KuXxNvBHA7O80ndoe0LAhW0BbE7U9uMz45hJnkTgytGP4Ktat8Y+pi0sEJl/XzVFIHv5fbGchwcl3pUXkqCd7l89p3c+3262sGsdlg2pCYYt01Lpyj+XQiY9TAOo43t72VwIQOA6zo0nJju9BR2DxTpmy2dkGqD8lq55scCV3QzUIxyerc+VObBWChz9aigdWmIX4ruwnDr+UB6ZkOwAie8k7NaUNYyBKNYeX3TXFE/uETg3sfa7CQ/NGY3pT3x41hivVrVSkYkTWQ==
    admin-user: AgCUOVZkLeQeQM39ig3DRQS16pMr6n5Dd+z0ELsF3bl5coThukMuA7NWEKOSKe3Rx3kptWljitCnoez/WLogOGBom4uLqxd8imevMsmDD4F0e3HrS/2cBxMm2sSMvYOpoRq91nxUbePZMOEdFyzOC8HC1P2Ax7X+ZsRWki2X5n4Vd4oC7N2ln6q10XeL1yFizRlpa89EpBxzVBKlPzoMLRRjY+6PN8V5pdkIXbHMSR94FWohEebZNhrDXKeYz33pSnp3/WQdFtDtazvvqWpnFsF3SpfBuofhZW0mNFkP4UdPlpbzVonbR2vzf4j+LsJbeTpomYJqgadmjTqLRwYr9gQbnrJEVKnDjfmDBzgK5XkwcF4DgFA3qAWBWioWjNYyWpom91/LP6+yZISKxEH+yc5bMSqx2yH3dekFci0dZIUNPgqeplMScCqvySvOJEm9Rj1TmCJLhgTT1gO/F09Us4Bi3cS9TbPmcBGwwcxq0NglVBjhGe0b9vDi9omZGDuhS1pIfEkszhiUdstAmO1fkr7Y++2mu+MO5tKQBISWweHD/NtOmzbXwzqBNtR6l5yj1hTPKQS9A3Wvy5nMhuYupdcIiG/PC5koojEJYuMVeCFxct7iZy5oEYXZoKIQausiTOIq3CcqweefXMMuf4gRjtrqQ79tYpUA3+EkpuuU6yfDUWbbQMXexgTtYWk+aJBSMIl51zWZ2A==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
