---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: akkoma-postgresql
  namespace: akkoma-staging
spec:
  encryptedData:
    postgres-password: AgA1i4Ch6LURaInDjcTIpvgZBZd7z5T3iGxC6a6gBLtG19g+Wb4QLOdavKHqogbt0R1ts2LG4absw9AqcESVFtJYdm4P7wc+8duWG0ck0YMPwzJy8lKSoi21gFIn9IlWJ7Fsu3wzMSuYJIs8hIoGSRXARfbNGkRYuvets27Se9hOVvGHCoipnAeXsqoJrTC6z5gq+yKhKBz63I3OP5eLn5Uxhit5WHPbNySIAZlKcqc9s84un8LZFWepW5aGryruE6H+rUbMNoShROBfo2Uw8z3xZe2qEtUaKCo5SgeLgmFE1bQyE/XvX1n8WCo2mRPgkaG3O2PlvjQ4bIRPZSNygfu2qasgb76ne+lJn7GzJMnNj19MEL742vSSp96CuubfnxFi3TRrxk3ApLTWCbYJJw2C4Jd7/L3JwWSmNQ8uPjajHEaXneF4PE2+7lcL4wbWGZX6EGxGY1DM1HJGcgSESH2l60dSUD+C3GchTDkKu3kISEUASpyU6MiKyXI2C400dvueJXMhWNsxenMi/nVpyjG6idyzk2hF1a/FnjdmIt1qfuo/3QKc2pwQE8bQLMYa0JZCZ7KpKcgLGBn1mpFwZjEka/UoMfjlt0QeXO6KZwSl4RPdHE9FxjdVldCGk2zm3mdWncz6HKWfAU0S9vI9cOZCCxpeLYpvAApSvzjpLluq7G3YcVi1RSNyQ7b0QhAoqqC4z5TlGE+Cqp+MwGisSKuMyyMpMyHZSPl8gCSDZ4LXxw==
  template:
    metadata:
      name: akkoma-postgresql
      namespace: akkoma-staging
