---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: soju-admin
  namespace: soju-dev
spec:
  encryptedData:
    admin-password: AgBWUrI1CDllgfMhdVN0KC+bBEvego2KUfvAcru3jyNglhzuG4ML6tiWwfxy+aax3Chk/l9xean1gpfNuk/DinsChmgwMh6WCykVO4JhuoEp/TjZAGLWQ4mqiV0Vhhs4T9aJTfmeWo/rhqtnXy6HvWAOjFvigzDw3wPq56BSSMocu6lGtOKxj1SmAhmvQozkppSGQZhJfqy8Qioh3jzw36/YF/AXDQH5bWDu+NJr81pqqT6cmPEFaa1auKPNUEl6UNw9U4MxykTmpGwvMVbf1+s512nAxpUm/VoZXwDiP6l/V4LikqT65W1+RK0hcpCrEzJGqY8JrDk2p92YW9mUwmPaV/idCxVTq2dwiom+QnjdzgsC06v5oNkE43QpHB5a03H9Gg7jKA9V5PJ99XuZUXztOq6CYPhJLftEopuKEhvO7mNM4F8n+z4OQv5EHs8QQ9MfHUlxeXOhc8FNuSRL9PDQhdQxO3Ph6NTphEGSQqgHSIEqMqTK4e9RN5fkHEgH7Tc7ZPU9u17IIx4dh8Nikt//QK8DZiL80X4hXcNcctp8zZUJJl35zRzA2VmlLGMtbmUd+HlvLEVLDvizIoAiGdZ4w6Y3M5YNx0Kr8cYm+K2kR0TcMmCFMsgXw/+JvUtLC6/rYzGL6QNq0JiLZAP58NL+A3Tw7Nwf72GWf/DhjXIl6Tek9zopx54s3nrjNY7tyP+U5TCmrs+T7kmppMIiQhwxwgDFP6koyi0=
    admin-username: AgAhNmZujrWUW2dLZMEfO2o8uAdB3wJP1xN7/puI5EjcByEfb4+VwzyHFX3Yt8RWRAoA13tOspR3PdbzObtOtVUYqEy/8s51FrXd2ikGvXuTlLArliXE1oIIvBpmQ15URqsX32TqUAaH9pCk30IamosJx0QmuGiWfwtrpCeV5OWBVgsJiMCUe/4zMKhAMpfjdjJ0k+MlKRMNkGJ+k9CHtZzM4zJjRwqCMaDXjE1c0U/UC9rxbMyA0kqcuwTqW7bVlePS4yaQqMKxi6LvwPtzl5di/KZu5PeFY72oHRSUgBiqf/C2I344moX3Sbc5zUK7D389sh+/9BPJ1CQkdqyO49X5olWeOfyTnBC/9sKk2g2M09HEkq9M3Mu1Sucdme4Gm2dniQI9g3htKteQZy6gCMETz7AJ2nnM9ujf3HuApzuDCyIx0tOLV13pNNRuW9U5flmSLJeK+OSv4DMhYekOODvxZzAA098/gFQtGyVYgty5m0It0WGYP4PPJ2Cdw8r1WI8cJf/M/OElfb3pWkSDriSLDIPShwRbkhhrgKfB6CFhfkZgBR0cJh1hXUkkw4YkSh2EA61jMca/mEeGda3EfRy75uqLsPM+bMGQ/0ck4tmVHFFDYp1t7zjPAUBhTQzBcpHvmKpSdlypsM77aaW0wtOTidxTWhMSnMl1iR2pcAlWrSkQaf9zUw0JJIAkT6NE9dwBQiCXIg==
  template:
    metadata:
      name: soju-admin
      namespace: soju-dev
