---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: akkoma-postgresql
  namespace: akkoma-dev
spec:
  encryptedData:
    postgres-password: AgAq57WNMK0zeSplbTD+2/THnJnL6uyatUz9s6ot+Wi1FdqbbfLAcn6Mz3o17JuobuEpo+xFsIwK1Y749y9o/NKQodVZCMUmQc9ib5uKe3IC5xJSxdnXtjNLTHjnjDSM3a0FcWS3spVDJxVlPyPDETVcjN8n2IQGG0jQEfUpjxEZoM3nUGXgv6E99PoXWI7roRHaZCo54mYLgA++5/RlOrmN+mXNST1V1dDemMKgtWuK2act/+CNoif7dkeQSteWv28FRmkv5iYlq4mb2146UkBEwCJBrxWQkmtpx0RkGVxFVj4LYWSehpZSCw2r6oLvQKUbDq+wHIyfkJ2r2FqdV7/hv0y0wZBuNgyLxewdOmWLJCGMeE8Bq+v28iwjcy4yOp9ML5WLb++KSxuu/RZvYQrmBEVp8XkdfOjp8Q+LdiBCSjpHmJNVuY/kOLgDIFyKbbnbMa8VN/HDG8sL90UIofxH2ZdhCW7xC3xbr//1o6Omfp0mEaBjstlJP1bwootipuK8Q/Nl3vSVMWkUXw4gED/ZTvp5Lx3jIkcftZOOI63Inc1hfb/DaplKrXKL126nKUSZ/A9clO55/HIQBZvw2dY9N8L835cx0lDv6z/CNOmLK+4uTiEebXtDeHIHl0MVZclDJQgSiMZiEbnu9WdDRD+MActGqpkV3AXx4OF+XdGnJKEbRcRGlomTwfkv075TlLJVg883KmxACfUiIYEiq7k4vybt8yEslUte0yjXoafZCQ==
  template:
    metadata:
      name: akkoma-postgresql
      namespace: akkoma-dev
