---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: soju-admin
  namespace: soju-staging
spec:
  encryptedData:
    admin-password: AgAv4udyeSdM4mtjt2XUd+GbFm5h1h3ecfuwXd11LijaWf8fopOFfZsySIYtTklCZy/4JqlNXwtFNzY0N8Gp6CH2p9rIKKQ27irIw+XRwNPdIJ/YjTmKnUchK6GPI5a8PWMBeCUMFTOZG45FoO93VTD+5BL1ggy3fllW1qwMflkLWGR/XT4D4uZaYcztiIej7xSD3JthgPPvqAowxAaSSXNouwvCv7fB+vhy665rdrmFj0qefGmlKJHvRt/+jN9WdJntWbhMPBaL3v/vl9b+Dem23UYJtm/rkrCIgzHEYoCbdPV14lYB4JtmyU8E10L+D7uXt+CKtToxgmpWIsLDFwHq1bA4idktV/zRkYqI/J+gzgkmPyXA94cnb/6fXVcQ8KL+bQlc5Kj5OYGmmQR49YuUFI6oLN33x1Skr29DY8+Cf6tvxZRc+lYxWFUJCmAUi/d8KyYc9XoCjJJ6P6GmcPJJ7ifdDj/wMTgT+Q3qHLgS4FPNYhTnXWBbDj7JN9kR28KI9BuSYCGqrV0XZ41vkjRdc+0zm2bShF5CxIvLO6Ja1/dHNa9FiRnHuzgB28KvSBUgLEeIFeZZ/X2+nZjm+RnnICx3k/gcsnX2Lc4MStdf40ixz87vs6l1wkFVdGFVQPB4XdF2Zn1R/XrUF5FEk/i3nOcfkwGKxeZ+Jms5a0vPAPaK0iBHYAXTFt+HxfQYe6O2k1hoavxbSunZqHUQIoOfCE4Ad0UHuMA=
    admin-username: AgCmmGzTOZ4tryMq93mzNk5sx3oSs4AYyQthyh7OsyUlbQDkbORiLuZY8yKxccGokkbYt/X9wiHfLClxDVXATqkxkyoPPvZ25Et7PuYNCQbiUcfTdg7xjTx75tSZSiHG8JeCdAtjvpT0lY7GtEq+k81hLKLVWCEKtkJWGEifACjZA43jvU7YdTJ8Fq3SK/M5k2LsRQ8NuiO72zBiq7AJjedAgmZWSinGA2M5Cp26rreA02OBdieF7UfdhD3MqbwaAThW2Mcz9Vze9oJlVtKWmwt1fJa9+2mSTp6MDdqbm4Clae+l8mT43TsWdE6nKBPm92HyLD2TmOy0tcKALbkQcr82h+oII4ImcucpkJUrqY3zAEOeACVRJsUR0BlvJDzhye4Mh+AA4fENnRf49yFv2eEJRGXNSAZZEwcDLSTJGAaC1thqUs2M86F1uBQrOBPOEnXdc5DHL+Xz+ONsaG2tCE7pRdHdtXnWzkxj1uxnJbg7EWP4ku9U/OhRicUVPL1Bs03d8QWIQYRuGflK8UKoVBOgTQxtGtPZTYDR4yRBM/2Yw8ige3YbcKkHMy4vho24/i57k/Myi9+izHmn3cnJpg+1YZWDodvv4l2ybIePddDDGtnMwkB9idaKtE8tvZyHfFkqJARJy+0jzJ2WG9G/PNslUtxMnu973pkK5+QHuMH68WB+zRTWBc4u0PbOUZfShIiJc/81gQ==
  template:
    metadata:
      name: soju-admin
      namespace: soju-staging
